Numpy: Numerical python a python library used in python when working with numerical data

Provides powerful n-dimensional array object and many maths data computation that work on this arrays and many constant variables that are related to maths

Characterstics of Numpy arrays
-> data types
-> homogenous data (can contain only values of single data type)
-> 

In [1]:
import numpy as np

In [4]:
a=np.zeros(16)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a=a.reshape(4,4)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
a=np.empty((2,3),dtype='i4')


In [22]:
a.dtype

dtype('int32')

In [24]:
np.full((4,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [26]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(-10,10,5)

array([-10,  -5,   0,   5])

In [28]:
np.array([(1,3),(2,3)])

array([[1, 3],
       [2, 3]])

In [8]:
type(np.array([(1,3),(2,3)]))

numpy.ndarray

In [29]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [30]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [31]:
a.dtype

dtype('int32')

In [32]:
a=a.astype('int')

In [33]:
a.dtype

dtype('int32')

In [34]:
a.itemsize

4

In [35]:
a

array([[-1655829952,         541,           0],
       [          0,     3014753,         100]])

In [39]:
a[0][0]

1

In [46]:
a[0][0]=3

In [41]:
a

array([[      1,     541,       0],
       [      0, 3014753,     100]])

In [48]:
np.save("numpyarray2",a,allow_pickle=False)

In [14]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
xs1=[[1,3,4],[1,3,2],[6,7,8]]
xs1=np.array(xs1)

In [16]:
xs1[0:3,1:3]

array([[3, 4],
       [3, 2],
       [7, 8]])

In [17]:
xs2=np.arange(1,17,1)
xs2=xs2.reshape(4,4)
xs2.shape
xs2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
xs2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [19]:
for x in (np.ndenumerate(xs2)):
    print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)
((2, 0), 9)
((2, 1), 10)
((2, 2), 11)
((2, 3), 12)
((3, 0), 13)
((3, 1), 14)
((3, 2), 15)
((3, 3), 16)


In [20]:
for x in np.nditer(xs2):
    print(x,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [21]:
print(xs2)
type(xs2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


numpy.ndarray

In [22]:
xs2=xs2.reshape(2,8)
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [23]:
xs2.transpose()

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])

In [24]:
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [30]:
np.unique(xs2,return_index=True,axis=0)

(array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([0, 1], dtype=int64))

In [31]:
str="hello"

In [33]:
str2=['h','e','l']

In [32]:
str[::-1]

'olleh'

In [35]:
str2.reverse()

In [36]:
str2

['l', 'e', 'h']

In [25]:
t1=np.arange(1,20,1)

In [31]:
t1[0:2]

array([1, 2])

In [39]:
np.argmax(xs2,axis=0)

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [36]:
np.array_split(xs2,3,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [42]:
xs2>10

array([[False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True]])

In [39]:
type(np.where(xs2>10))

tuple

In [44]:
[*(zip(np.where(xs2>0)[0],np.where(xs2>0)[1]))]

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)]

In [27]:
t1[t1>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.concatenate((xs2,xs2),axis=0)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [163]:
np.concatenate((xs2,xs2),axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16,  9, 10, 11, 12, 13, 14, 15, 16]])

In [187]:
arr=np.array([[1,2,4]])
np.append(arr,arr,axis=0)

array([[1, 2, 4],
       [1, 2, 4]])

In [188]:
np.append(arr,arr,axis=1)
arr

array([[1, 2, 4]])

In [45]:
np.sum(xs2)

136

In [167]:
xs2.sum()

136

In [168]:
np.std(xs2,axis=1)

array([2.29128785, 2.29128785])

In [169]:
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [170]:
xs3=np.arange(16,0,-1)
xs3=xs3.reshape(4,4)
xs3

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [171]:
np.sort(xs3,axis=0)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [172]:
np.sort(xs3,axis=1)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [173]:
np.where(xs3>10)
# type(np.where(xs3>10)[0])

(array([0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1], dtype=int64))

In [174]:
xs3[np.where(xs3>10)]

array([16, 15, 14, 13, 12, 11])

In [175]:
xs3[xs3>10]

array([16, 15, 14, 13, 12, 11])

In [183]:
a = np.array([1,2,3,4,5,6]) 
np.save('outfile',a)

In [184]:
b=np.load('outfile.npy')
b

array([1, 2, 3, 4, 5, 6])

In [178]:
s2=[1,2,3,5]
npa1=np.array(s2)
print(npa1)

[1 2 3 5]


In [181]:
np.where(npa1>2)

(array([2, 3], dtype=int64),)

In [182]:
npa1>2

array([False, False,  True,  True])

In [43]:
arr = np.array([1,2,3,4,1,2])
arr

array([1, 2, 3, 4, 1, 2])

In [44]:
np.put(arr,[1,2],[6,7])
arr

array([1, 6, 7, 4, 1, 2])

In [54]:
A = np.array([[3,4,5,2],[6,7,2,6]])
B = np.array([[3,4,5,2],[6,7,2,6]])

In [50]:
np.array_split(A,2,axis=1)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [55]:
A==B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
np.equal(A,B)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
np.pi

3.141592653589793