Numpy: Numerical python a python library used in python when working with numerical data

Provides powerful n-dimensional array object and many maths data computation that work on this arrays and many constant variables that are related to maths

Characterstics of Numpy arrays
-> data types
-> homogenous data (can contain only values of single data type)
-> 

In [78]:
import numpy as np

In [79]:
a=np.zeros(16)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
a=a.reshape(8,2) 
# rows, cols
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
a.reshape(4,-1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
a.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [83]:
a=np.empty((2,3),dtype='i4')

In [84]:
np.empty((2,3),dtype='float')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
a.dtype

dtype('int32')

In [86]:
np.full((4,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [87]:
np.arange(1,11,1,dtype="float")

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [88]:
np.arange(1,11,1,dtype="float").itemsize

8

In [89]:
np.arange(-10,10,5)

array([-10,  -5,   0,   5])

In [90]:
np.array([(1,3),(2,3)])

array([[1, 3],
       [2, 3]])

In [91]:
np.array(((1,2),(3,4))).ndim

2

In [92]:
type(np.array([(1,3),(2,3)]))

numpy.ndarray

In [93]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [94]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [95]:
a.dtype

dtype('int32')

In [96]:
a=a.astype('int')

In [97]:
a.dtype

dtype('int32')

In [98]:
a.itemsize

4

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
a[0][0]

1

In [101]:
a[0][0]=3

In [103]:
a

array([[3, 2, 3],
       [4, 5, 6]])

In [104]:
np.save("numpyarray2",a,allow_pickle=False)

In [105]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
xs1=[[1,3,4],[1,3,2],[6,7,8]]
xs1=np.array(xs1)

In [163]:
print(xs1)
print(xs1[0:4,1:3])

[[1 3 4]
 [1 3 2]
 [6 7 8]]
[[3 4]
 [3 2]
 [7 8]]


In [107]:
xs1[0:3,1:3]

array([[3, 4],
       [3, 2],
       [7, 8]])

In [108]:
xs2=np.arange(1,17,1)
xs2=xs2.reshape(4,4)
xs2.shape
xs2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [164]:
xs2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [166]:
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [175]:
xs2.sort()
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [165]:
for x in (np.ndenumerate(xs2)):
    print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((0, 4), 5)
((0, 5), 6)
((0, 6), 7)
((0, 7), 8)
((1, 0), 9)
((1, 1), 10)
((1, 2), 11)
((1, 3), 12)
((1, 4), 13)
((1, 5), 14)
((1, 6), 15)
((1, 7), 16)


In [111]:
for x in np.nditer(xs2):
    print(x,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [112]:
print(xs2)
type(xs2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


numpy.ndarray

In [113]:
xs2=xs2.reshape(2,8)
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [114]:
xs2.transpose()

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])

In [115]:
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [116]:
np.unique(xs2,return_index=True,axis=0)

(array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([0, 1], dtype=int64))

In [117]:
str="hello"

In [118]:
str2=['h','e','l']

In [119]:
str[::-1]

'olleh'

In [120]:
str2.reverse()

In [121]:
str2

['l', 'e', 'h']

In [122]:
t1=np.arange(1,20,1)

In [123]:
t1[0:2]

array([1, 2])

In [124]:
np.argmax(xs2,axis=0)

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [125]:
np.array_split(xs2,3,axis=1)

[array([[ 1,  2,  3],
        [ 9, 10, 11]]),
 array([[ 4,  5,  6],
        [12, 13, 14]]),
 array([[ 7,  8],
        [15, 16]])]

In [126]:
xs2>10

array([[False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True]])

In [176]:
np.where(xs2>10)

(array([1, 1, 1, 1, 1, 1], dtype=int64),
 array([2, 3, 4, 5, 6, 7], dtype=int64))

In [127]:
type(np.where(xs2>10))

tuple

In [180]:
[*zip((1,2),(3,4))]

[(1, 3), (2, 4)]

In [183]:
[*(zip(np.where(xs2>10)[0],np.where(xs2>10)[1]))]

[(1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7)]

In [129]:
t1[t1>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [130]:
np.concatenate((xs2,xs2),axis=0)


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [131]:
np.concatenate((xs2,xs2),axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16,  9, 10, 11, 12, 13, 14, 15, 16]])

In [132]:
arr=np.array([[1,2,4]])
np.append(arr,arr,axis=0)

array([[1, 2, 4],
       [1, 2, 4]])

In [133]:
np.append(arr,arr,axis=1)
arr

array([[1, 2, 4]])

In [134]:
np.sum(xs2)

136

In [135]:
xs2.sum()

136

In [136]:
np.std(xs2,axis=1)

array([2.29128785, 2.29128785])

In [137]:
xs2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [138]:
xs3=np.arange(16,0,-1)
xs3=xs3.reshape(4,4)
xs3

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [139]:
np.sort(xs3,axis=0)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [140]:
np.sort(xs3,axis=1)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [141]:
np.where(xs3>10)
# type(np.where(xs3>10)[0])

(array([0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1], dtype=int64))

In [142]:
xs3[np.where(xs3>10)]

array([16, 15, 14, 13, 12, 11])

In [143]:
xs3[xs3>10]

array([16, 15, 14, 13, 12, 11])

In [144]:
a = np.array([1,2,3,4,5,6]) 
np.save('outfile',a)

In [145]:
b=np.load('outfile.npy')
b

array([1, 2, 3, 4, 5, 6])

In [146]:
s2=[1,2,3,5]
npa1=np.array(s2)
print(npa1)

[1 2 3 5]


In [147]:
np.where(npa1>2)

(array([2, 3], dtype=int64),)

In [148]:
npa1>2

array([False, False,  True,  True])

In [149]:
arr = np.array([1,2,3,4,1,2])
arr

array([1, 2, 3, 4, 1, 2])

In [150]:
np.put(arr,[1,2],[6,7])
arr

array([1, 6, 7, 4, 1, 2])

In [151]:
A = np.array([[3,4,5,2],[6,7,2,6]])
B = np.array([[3,4,5,2],[6,7,2,6]])

In [152]:
np.array_split(A,2,axis=1)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [153]:
A==B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [154]:
np.equal(A,B)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [155]:
np.pi

3.141592653589793